language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
install:
  - "pip install -r test-requirements.txt"
env:
  - HTTPWATCHER_TEST_CHECK_DELAY="5.0"
script:
  - "python -m tornado.test.runtests tests.test_fs_watcher"
  - "python -m tornado.test.runtests tests.test_server"
